apiVersion: apps/v1
kind: Deployment
metadata:
  name: oficina-api
  namespace: ${ENV}
  labels:
    app: oficina-api
    tags.datadoghq.com/env: "${ENV}"
    tags.datadoghq.com/service: oficina-api
    tags.datadoghq.com/version: "${VERSION}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oficina-api
  template:
    metadata:
      labels:
        app: oficina-api
        tags.datadoghq.com/env: "${ENV}"
        tags.datadoghq.com/service: oficina-api
        tags.datadoghq.com/version: "${VERSION}"
      annotations:
        ad.datadoghq.com/oficina-api.logs: '[{"source": "python", "service": "oficina-api"}]'
        ad.datadoghq.com/oficina-api.checks: |
          {
            "http_check": {
              "init_config": {},
              "instances": [
                {
                  "name": "oficina-api-${ENV}",
                  "url": "http://%%host%%:5000/api/health",
                  "timeout": 5,
                  "tags": ["service:oficina-api", "env:${ENV}"]
                }
              ]
            }
          }
    spec:
      containers:
        - name: oficina-api
          image: ${IMAGE}
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: oficina-config
            - secretRef:
                name: oficina-secret
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
          readinessProbe:
            httpGet:
              path: /api/ready
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
