apiVersion: v1
kind: Secret
metadata:
  name: oficina-secret
  namespace: ${ENV}
type: Opaque
stringData:
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
  JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
  WEBHOOK_TOKEN: "${WEBHOOK_TOKEN}"
  ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
