from abc import ABC, abstractmethod


class ClienteRepositoryPort(ABC):
    @abstractmethod
    def listar(self): ...
    @abstractmethod
    def buscar_por_id(self, id_cliente): ...
    @abstractmethod
    def buscar_por_documento(self, documento): ...
    @abstractmethod
    def criar(self, nome, documento): ...
    @abstractmethod
    def atualizar(self, id_cliente, nome, documento): ...
    @abstractmethod
    def deletar(self, id_cliente): ...


class VeiculoRepositoryPort(ABC):
    @abstractmethod
    def listar(self): ...
    @abstractmethod
    def buscar_por_id(self, id_veiculo): ...
    @abstractmethod
    def buscar_por_placa(self, placa): ...
    @abstractmethod
    def criar(self, placa, marca, modelo, ano): ...
    @abstractmethod
    def atualizar(self, id_veiculo, placa, marca, modelo, ano): ...
    @abstractmethod
    def deletar(self, id_veiculo): ...


class PecaRepositoryPort(ABC):
    @abstractmethod
    def listar(self): ...
    @abstractmethod
    def buscar_por_id(self, id_peca): ...
    @abstractmethod
    def criar(self, nome, valor_unitario, estoque): ...
    @abstractmethod
    def atualizar(self, id_peca, nome, valor_unitario, estoque): ...
    @abstractmethod
    def deletar(self, id_peca): ...


class ServicoRepositoryPort(ABC):
    @abstractmethod
    def listar(self): ...
    @abstractmethod
    def buscar_por_id(self, id_servico): ...
    @abstractmethod
    def criar(self, nome, valor): ...
    @abstractmethod
    def atualizar(self, id_servico, nome, valor): ...
    @abstractmethod
    def deletar(self, id_servico): ...


class OrdemServicoRepositoryPort(ABC):
    @abstractmethod
    def listar_ativas(self): ...
    @abstractmethod
    def buscar_por_id(self, id_os): ...
    @abstractmethod
    def criar(self, id_cliente, id_veiculo): ...
    @abstractmethod
    def atualizar_status(self, id_os, novo_status, fechar=False): ...
    @abstractmethod
    def adicionar_peca(self, id_os, peca, valor_total): ...
    @abstractmethod
    def adicionar_servico(self, id_os, servico, valor_total): ...
    @abstractmethod
    def buscar_pecas(self, id_os): ...
    @abstractmethod
    def buscar_servicos(self, id_os): ...
    @abstractmethod
    def tempo_medio(self): ...


class UsuarioRepositoryPort(ABC):
    @abstractmethod
    def buscar_por_username(self, username): ...
